//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRS.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của bạn đang bị cấm hoạt động..
        /// </summary>
        public static string AccountIsBanned {
            get {
                return ResourceManager.GetString("AccountIsBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã thử đăng nhập quá số lần cho phép. Tài khoản của bạn sẽ bị khóa trong {0} phút..
        /// </summary>
        public static string AccountIsLocked {
            get {
                return ResourceManager.GetString("AccountIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe has been approved successfully..
        /// </summary>
        public static string ApproveRecipeSuccess {
            get {
                return ResourceManager.GetString("ApproveRecipeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word has been updated successfully..
        /// </summary>
        public static string ApproveUpdatedWordSuccess {
            get {
                return ResourceManager.GetString("ApproveUpdatedWordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word has been approved successfully..
        /// </summary>
        public static string ApproveWordSuccess {
            get {
                return ResourceManager.GetString("ApproveWordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin admin không thể thay đổi..
        /// </summary>
        public static string CannotChangeAdminInfo {
            get {
                return ResourceManager.GetString("CannotChangeAdminInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản admin không thể bị xóa..
        /// </summary>
        public static string CannotDeleteAdminInfo {
            get {
                return ResourceManager.GetString("CannotDeleteAdminInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên mục không tồn tại hoặc bị xóa..
        /// </summary>
        public static string CategoryNotExisted {
            get {
                return ResourceManager.GetString("CategoryNotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung không thể bỏ trống..
        /// </summary>
        public static string ContentIsEmpty {
            get {
                return ResourceManager.GetString("ContentIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền xóa câu trả lời của người khác..
        /// </summary>
        public static string DeleteAnswer_NoPermission {
            get {
                return ResourceManager.GetString("DeleteAnswer_NoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền xóa bình luận của người khác..
        /// </summary>
        public static string DeleteComment_NoPermission {
            get {
                return ResourceManager.GetString("DeleteComment_NoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News has been deleted successfully..
        /// </summary>
        public static string DeleteNewsSuccess {
            get {
                return ResourceManager.GetString("DeleteNewsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe has been deleted successfully..
        /// </summary>
        public static string DeleteRecipeSuccess {
            get {
                return ResourceManager.GetString("DeleteRecipeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role has been deleted successfully..
        /// </summary>
        public static string DeleteRoleSuccess {
            get {
                return ResourceManager.GetString("DeleteRoleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa chuyên mục thành công..
        /// </summary>
        public static string DeleteTipCategorySuccess {
            get {
                return ResourceManager.GetString("DeleteTipCategorySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip has been deleted successfully..
        /// </summary>
        public static string DeleteTipSuccess {
            get {
                return ResourceManager.GetString("DeleteTipSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated word has been deleted successfully..
        /// </summary>
        public static string DeleteUpdatedWordSuccess {
            get {
                return ResourceManager.GetString("DeleteUpdatedWordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been deleted successfully..
        /// </summary>
        public static string DeleteUserSuccess {
            get {
                return ResourceManager.GetString("DeleteUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word has been deleted successfully..
        /// </summary>
        public static string DeleteWordSuccess {
            get {
                return ResourceManager.GetString("DeleteWordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có tên nguyên liệu này. Bạn hãy kiểm tra lại trước khi muốn thêm tên nguyên liệu mới..
        /// </summary>
        public static string Dictionary_DublicateName {
            get {
                return ResourceManager.GetString("Dictionary_DublicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không được phép sửa bài này..
        /// </summary>
        public static string EditNews_NotAllowed {
            get {
                return ResourceManager.GetString("EditNews_NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không được phép sửa câu hỏi này..
        /// </summary>
        public static string EditQuestion_NotAllowed {
            get {
                return ResourceManager.GetString("EditQuestion_NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không được phép sửa công thức này..
        /// </summary>
        public static string EditRecipe_NotAllowed {
            get {
                return ResourceManager.GetString("EditRecipe_NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không được phép sửa bài này..
        /// </summary>
        public static string EditTip_NotAllowed {
            get {
                return ResourceManager.GetString("EditTip_NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ email không tồn tại..
        /// </summary>
        public static string EmailIsNotExisted {
            get {
                return ResourceManager.GetString("EmailIsNotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ email đã được sử dụng..
        /// </summary>
        public static string EmailIsUsed {
            get {
                return ResourceManager.GetString("EmailIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dung lượng ảnh vượt quá mức cho phép..
        /// </summary>
        public static string ExceedMaxContentLength {
            get {
                return ResourceManager.GetString("ExceedMaxContentLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra. Thực hiện tác vụ không thành công..
        /// </summary>
        public static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category not found..
        /// </summary>
        public static string GetCategory_NotFound {
            get {
                return ResourceManager.GetString("GetCategory_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role not found..
        /// </summary>
        public static string GetRole_NotFound {
            get {
                return ResourceManager.GetString("GetRole_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung không tồn tại..
        /// </summary>
        public static string GetTagCategory_NotFound {
            get {
                return ResourceManager.GetString("GetTagCategory_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không tồn tại..
        /// </summary>
        public static string GetUser_NotFound {
            get {
                return ResourceManager.GetString("GetUser_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ hỗ trợ định dạng ảnh JPG và PNG.
        /// </summary>
        public static string ImageExtensionNotAllowed {
            get {
                return ResourceManager.GetString("ImageExtensionNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích thước ảnh quá nhỏ..
        /// </summary>
        public static string ImageTooSmall {
            get {
                return ResourceManager.GetString("ImageTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập hoặc mật khẩu không chính xác..
        /// </summary>
        public static string IncorrectLoginInfo {
            get {
                return ResourceManager.GetString("IncorrectLoginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ không đúng..
        /// </summary>
        public static string IncorrectOldPassword {
            get {
                return ResourceManager.GetString("IncorrectOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a category with the same name..
        /// </summary>
        public static string InsertCategory_DuplicateName {
            get {
                return ResourceManager.GetString("InsertCategory_DuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo tin tức mới thành công..
        /// </summary>
        public static string InsertNewsSuccess {
            get {
                return ResourceManager.GetString("InsertNewsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe Category has been inserted successfully..
        /// </summary>
        public static string InsertRecipeCategorySuccess {
            get {
                return ResourceManager.GetString("InsertRecipeCategorySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Recipe Category has been inserted successfully..
        /// </summary>
        public static string InsertRecipeSmallCategorySuccess {
            get {
                return ResourceManager.GetString("InsertRecipeSmallCategorySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo công thức nấu ăn thành công..
        /// </summary>
        public static string InsertRecipeSuccess {
            get {
                return ResourceManager.GetString("InsertRecipeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a role with the same name..
        /// </summary>
        public static string InsertRole_DuplicateName {
            get {
                return ResourceManager.GetString("InsertRole_DuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role has been inserted successfully..
        /// </summary>
        public static string InsertRoleSuccess {
            get {
                return ResourceManager.GetString("InsertRoleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a tag category with the same name..
        /// </summary>
        public static string InsertTagCategory_DuplicateName {
            get {
                return ResourceManager.GetString("InsertTagCategory_DuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên mục này đã tồn tại..
        /// </summary>
        public static string InsertTipCategory_DuplicateName {
            get {
                return ResourceManager.GetString("InsertTipCategory_DuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo chuyên mục mới thành công..
        /// </summary>
        public static string InsertTipCategorySuccess {
            get {
                return ResourceManager.GetString("InsertTipCategorySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mẹo vặt mới thành công..
        /// </summary>
        public static string InsertTipSuccess {
            get {
                return ResourceManager.GetString("InsertTipSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm từ mới thành công. Ban quản trị sẽ kiểm tra độ chính xác trong thời gian sớm nhất..
        /// </summary>
        public static string InsertWordSuccess {
            get {
                return ResourceManager.GetString("InsertWordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập không thành công..
        /// </summary>
        public static string LoginFail {
            get {
                return ResourceManager.GetString("LoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức bạn tìm kiếm không tồn tại..
        /// </summary>
        public static string NewsNotExisted {
            get {
                return ResourceManager.GetString("NewsNotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu hỏi không tồn tại hoặc đã bị xóa..
        /// </summary>
        public static string QuestionNotExisted {
            get {
                return ResourceManager.GetString("QuestionNotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công thức nấu ăn không tồn tại chuyên mục nào..
        /// </summary>
        public static string RecipeCategoriesNotExisted {
            get {
                return ResourceManager.GetString("RecipeCategoriesNotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công thức nấu ăn không tồn tại hoặc bị xóa..
        /// </summary>
        public static string RecipeNotExisted {
            get {
                return ResourceManager.GetString("RecipeNotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mẹo vặt không tồn tại hoặc đã bị xóa..
        /// </summary>
        public static string TipNotExisted {
            get {
                return ResourceManager.GetString("TipNotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word has been unapproved successfully..
        /// </summary>
        public static string UnapproveWordSuccess {
            get {
                return ResourceManager.GetString("UnapproveWordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền truy cập trang này..
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin không thành công..
        /// </summary>
        public static string UpdateInformationFail {
            get {
                return ResourceManager.GetString("UpdateInformationFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi mật khẩu không thành công..
        /// </summary>
        public static string UpdatePasswordFail {
            get {
                return ResourceManager.GetString("UpdatePasswordFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi mật khẩu thành công..
        /// </summary>
        public static string UpdatePasswordSuccess {
            get {
                return ResourceManager.GetString("UpdatePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a role with the same name..
        /// </summary>
        public static string UpdateRole_DuplicateName {
            get {
                return ResourceManager.GetString("UpdateRole_DuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role has been updated successfully..
        /// </summary>
        public static string UpdateRoleSuccess {
            get {
                return ResourceManager.GetString("UpdateRoleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật chuyên mục thành công..
        /// </summary>
        public static string UpdateTipCategorySuccess {
            get {
                return ResourceManager.GetString("UpdateTipCategorySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin cá nhân đã được cập nhật..
        /// </summary>
        public static string UpdateUserProfileSuccess {
            get {
                return ResourceManager.GetString("UpdateUserProfileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been updated successfully..
        /// </summary>
        public static string UpdateUserSuccess {
            get {
                return ResourceManager.GetString("UpdateUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa từ thành công. Ban quản trị sẽ kiểm tra độ chính xác trong thời gian sớm nhất..
        /// </summary>
        public static string UpdateWordSuccess {
            get {
                return ResourceManager.GetString("UpdateWordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập đã tồn tại. .
        /// </summary>
        public static string UsernameIsUsed {
            get {
                return ResourceManager.GetString("UsernameIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không thể thích câu trả lời của chính mình..
        /// </summary>
        public static string VoteAnswer_SeftVoting {
            get {
                return ResourceManager.GetString("VoteAnswer_SeftVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không thể thích bình luận của chính mình..
        /// </summary>
        public static string VoteComment_SeftVoting {
            get {
                return ResourceManager.GetString("VoteComment_SeftVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không thể thích bài viết của chính mình..
        /// </summary>
        public static string VoteContent_SeftVoting {
            get {
                return ResourceManager.GetString("VoteContent_SeftVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ không tồn tại hoặc đã bị xóa..
        /// </summary>
        public static string WordNotExisted {
            get {
                return ResourceManager.GetString("WordNotExisted", resourceCulture);
            }
        }
    }
}
